name: Build

on:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files_yaml: |
           paper:
              - paper/**.md
              - paper/images/**

      - name: Run step if paper file(s) change
        if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.paper_all_changed_files }}
        run: |
          echo "One or more files in the paper folder has changed."
          echo "List all the files that have changed: $ALL_CHANGED_FILES"

      - name: Run pandoc and texlive install if paper file(s) change
        # if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        run: sudo apt-get update && sudo apt-get install pandoc texlive -y

      - name: Init tlmgr
        # if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        run: tlmgr init-usertree && sudo tlmgr update --all

      - name: Update tlmgr
        # if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        run: sudo tlmgr update --all
      