name: Build

on:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files_yaml: |
           paper:
              - paper/**.md
              - paper/images/**

      - name: Run step if paper file(s) change
        if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.paper_all_changed_files }}
        run: |
          echo "One or more files in the paper folder has changed."
          echo "List all the files that have changed: $ALL_CHANGED_FILES"

      - name: Install pandoc if paper file(s) change
        # if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        run: sudo apt-get update && curl -sLO https://github.com/jgm/pandoc/releases/download/3.1.12.1/pandoc-3.1.12.1-1-amd64.deb && sudo dpkg -i pandoc-3.1.12.1-1-amd64.deb && pandoc -v

      - name: Install texlive if paper file(s) change
        # if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        # run: sudo apt-get install texlive-full -y
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: texlive-full

      - name: Run paper pdf build if paper file(s) change
        # if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        run: cd paper && pandoc --bibliography article.bibtex --citeproc article.md -o article.pdf --from markdown --metadata-file=metadata.yaml --data-dir=../data --template eisvogel.tex --listings && pwd && ls -la

      - name: Upload article pdf if paper file(s) change
        # if: steps.changed-files-yaml.outputs.paper_any_changed == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          file: /home/runner/work/paper/paper/paper/article.pdf
          overwrite: true
          body: "Updated article.pdf"